### ISSUE TITLE
Create Overlapping Panels in Home Screen like Discord

### ISSUE THREAD

**Issue by toanbui217** [tunnvv/Nhom-6_INT3020-40#16]
### Description

Split **HomeScreen** into **ChannelScreen** and **ChatScreen** like how **Discord** works.

![discord](https://user-images.githubusercontent.com/62609188/195755610-5cb0d9c7-65d0-4ec3-9360-3b3c01d4d164.gif)

**Idea:**

Use the library [Overlapping Panels](https://github.com/blackmann/overlapping_panels), but it will cause a bit lag in animation when change side.

**Comment by buivantoanbg2001** [comment]
307ff6f716caf67715d7b05b60dbf67abf369978
