### ISSUE TITLE
How to create a sliding screen from the bottom up?

### ISSUE THREAD

**Issue by tunvx** [tunnvv/Nhom-6_INT3020-40#18]
I want to create a sliding bottom screen for basic UIs like a call screen, but flutter doesn't have wedgets available for that yet. Can someone help me figure this out?

**Comment by tunvx** [comment]
you can try using external package ![sliding up panel](https://pub.dev/packages/sliding_up_panel)

**Comment by tunnvv** [comment]
Hello, cảm ơn vì gợi ý của bạn, nó đã hoạt động
![] (https://github.com/tunnvv/Nhom-6_INT3020-40/blob/main/img/demo_discord_clone.gif)

**Comment by tunvx** [comment]
Hello, thanks for your suggestion, it worked
![] (https://github.com/tunnvv/Nhom-6_INT3020-40/blob/main/img/demo_discord_clone.gif)
